version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Download pack
          command: wget https://github.com/buildpacks/pack/releases/download/v0.21.1/pack-v0.21.1-linux.tgz
      - run:
          name: Extract pack
          command: tar xvf pack-v0.21.1-linux.tgz
      - run:
          name: Build application
          command: ./pack build jard-client --builder heroku/buildpacks:20 --buildpack https://cnb-shim.herokuapp.com/v1/mars/create-react-app
      - run:
          name: Deploy to docker hub
          command: bash docker_push.sh
workflows:
  default:
    jobs:
      - build:
          context: jard
          filters:
            branches:
              only: master
